# Generated by Django 5.2.6 on 2025-09-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildcatsIHUB_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link',
            new_name='github_url',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='live_demo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='project_screenshots/'),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_used',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='video_demo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
