# Generated by Django 5.2.8 on 2025-12-02 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Information Technology', 'Information Technology')], max_length=50)),
                ('year_level', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], max_length=20)),
                ('full_name', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('school', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('graduation_yr', models.TextField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('specialization', models.TextField(blank=True, null=True)),
                ('major', models.TextField(blank=True, null=True)),
                ('minor', models.TextField(blank=True, null=True)),
                ('courses', models.TextField(blank=True, null=True)),
                ('interests', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, default='avatars/default_profile.png', null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
