# Generated by Django 5.2.7 on 2025-11-30 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
